# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BirthRide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LambdaTimeline
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'GoogleMaps'
pod 'GooglePlaces'

end